### PR TITLE
IFOV + OFOV LLH tests

### PR DESCRIPTION
**Pull request by metalphase**
Adding a python script that performs the LLH ratio test statistic calculation for two sources, one IFOV and the other OFOV. The intention is that any additions to the codebase can be verified by test_likelihood_ratio_test_statistic.py such that the likelihood ratio test statistic is unchanged. 

The script and its necessary resources are contained in a new directory /tests in the base folder.

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Can you please replicate here previous documentation on the output of the tests, some stats on runtime, and the warnings produced?

Also rename this PR to to "IFOV + OFOV LLH tests"

**Comment by metalphase** [comment]
Running pytest on test_likelihood_ratio_test_statistic.py results in 2 passed and 725(!) warnings after 26.94s. The majority of these warnings were DeprecationWarnings such as: 

git_im1

and:

git_im2

However, among them were two other warnings, an AstropyUserWarning and a RuntimeWarning:

git_im3

git_im4

The runtime statistics from pytest-profiling are the following:

git_im5

**Comment by Tohuvavohu** [comment]
Looks pretty good to me.
Let's have a separate PR for tests on the background modelling.
@parsotat @jjd330, thoughts before merge?

**Comment by parsotat** [comment]
just to be sure, this has the updates from the new IFOV and OFOV changes and the results are identical to those before the changes were made to the IFOV and OFOV analyses? See https://github.com/Swift-BAT/NITRATES/issues/10

**Comment by Tohuvavohu** [comment]
Ah good point. No, this doesn't have the new `Sig_Bkg_Model` and new `LLH object LLH_webins2`

@metalphase can you implement this?
Follow what @jjd330 did here (https://github.com/Swift-BAT/NITRATES/pull/9) and Issue #10 that Tyler mentioned above, to change the way the calculation is done
you can see how its done in  do_llh_outFoV4realtime2.py

**Comment by jjd330** [comment]
Are we good with adding that much data into the repo? That looks like a few hundred MBs

**Comment by parsotat** [comment]
I am ok with the size of the files added for now

@metalphase If  your repository is up to date with my fork then you have all the changes that I made to the OFOV llh calculation (@jjd330 already made the changes for the IFOV portion of things and also tested it to make sure that we are getting consistent answers). My question is: if your repository has the changed OFOV calculations  do those reproduce the prior tests without the changes, can you test that my fork reproduces the old OFOV results?

**Comment by Tohuvavohu** [comment]
@parsotat 
This will require changes to the way the tests are implemented, since they currently use the old LLH_webins and compound_model, since @metalphase is not actually wrapping the do_llh_**FOV4realtime scripts in a test, but instead has rolled his own TS calculation based on the notebooks, see: https://github.com/parsotat/NITRATES/blob/d028de993690af56e2a23e3253f2e2a8856fbee6/tests/test_likelihood_ratio_test_statistic.py#L104

So these are mostly tests of the model classes, and relevant functions, then any particular script.
@metalphase let me know if anything is unclear in changing the tests for the new model and llh classes. Keep the old way as well, and just make new test functions for using the new classes (they are less flexible and we will want to maintain the ability to test the original formulation for other purposes).

**Pull request closed without merging**
