### PR TITLE
Add nitrates_reader functionality to NITRATES

### PR DESCRIPTION
**Pull request by Tohuvavohu**
This adds functionality to read  full rates, split rates, infov, outfov, and top results and output pandas data frames.
In addition, using read_results_dir it can parse in an entire directory and upload these results to the EchoLocation.
This requires having EchoAPI and an api_token.

It can be called as follows:

```
from nitrates.post_process.nitrates_reader import read_results_dirs
read_results_dirs(['path to results dir'],api_token, figures=False, test=True)
```

right now the Figures will fail, but all the results will be uploaded to EchoLocation.

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
This is the output of calling the function as above:
https://guano.swift.psu.edu/trigger_report?id=704768492
Full nitrates results but no figures.

**Comment by parsotat** [comment]
@Tohuvavohu the above link doesn't seem to work for me at least, can you post a screenshot?

**Comment by Tohuvavohu** [comment]
I deleted that test, it's just identical to the regular trigger report page but without figures.

**Comment by parsotat** [comment]
@Tohuvavohu I was getting an error at this line: `sctimes[i] = Clock(utctime=datetimes[i]).met` where the value of `sctimes[i]` is set to None. This leads to an error in this line: `attfile['QPARAM'][np.argmin(np.abs(attfile['TIME'] - sctimes[i]))]` which says: *** TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'.

My versions of swift tools was 2.4.8 and I just updated to version 3.0.16 and this seems to have fixed the error. Thus anyone else running into this issue should update their swifttools. 

Also, once you add the plotting, I will merge this PR.

**Comment by Tohuvavohu** [comment]
Plan is to implement figure generation on the server side at the API endpoint instead, so this is ready to merge.

**Pull request merged**
