### PR TITLE
IFOV and OFOV likelihood tests

### PR DESCRIPTION
**Pull request by metalphase**
Refer to the discussion in the previously closed PR https://github.com/parsotat/NITRATES/pull/5. Using analysis_for_imxy_square() as reference in do_llh_inFoV4realtime2.py, I've updated the test script to calculate sqrTS using Sig_Bkg_Model and LLH_webins2 as requested. This is captured in the function calculate_LLH_ratio_test_statistic(). The previous method using the compound model and LLH_webins has been renamed old_calculate_LLH_ratio_test_statistic() and is still available. 

@parsotat you asked to check that the calculations recreated the same results as the old method. These were my results:
For theta, phi = 38.541, 137.652, the value for sqrtTS using old_calculate_LLH_ratio_test_statistic() was 17.008497698693443 whereas with calculate_LLH_ratio_test_statistic() we now calculate 14.017985702679729. 

For theta, phi = 125.0, 25.0, we had 15.558480899442337 before , and now it is calculated at 13.728251640722451.

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
@metalphase I think there's something wrong with the commits on this PR, as it's saying that there are 'infinite files changed'.

The results from the old classes and new classes should match. 
Try and debug what the issue is, make sure you are actually passing all of the same parameters, bkgs, etc.

**Comment by Tohuvavohu** [comment]
Hi @metalphase any update here?

**Comment by metalphase** [comment]
@Tohuvavohu Sorry for the wait. I've been trying to reconcile the differences between the old and new versions of the test to which I've been able to narrow down where the difference is occurring. In the calculation of sqrtTS the good news is that the value for bkg_nllh is consistent between the old and new versions. bkg_nllh is calculated from sig_llh_obj which is LLH_webins and LLH_webins2 in the old and new versions. So this should be validation that the changes to LLH_webins and Sig_Bkh_Model aren't causing any dfferences in the calculation of bkg_nllh.
You can see in the screenshots the values in the old versus new versions of the test functions. 


Screenshot 2023-04-10 at 11 14 15 PM
Screenshot 2023-04-10 at 11 14 21 PM


So the differences are coming from the value of nllh[0] from the result of the minimization process of sig_miner. The minimizer is set up and run via the following lines of code:

Screenshot 2023-04-10 at 11 22 29 PM

Here I'm a bit stuck here as I'm not entirely sure whether this is an issue with my implementation of the minimizer or if this is actually a result of the new classes.

**Comment by Tohuvavohu** [comment]
Great sleuthing @metalphase !!
Can you share the entire `nllh` vector (ie not just the 0th element) for both the old and new calculation?

Tagging in @jjd330 as well

**Comment by metalphase** [comment]
@Tohuvavohu It looks like the vector has only the one entry in both cases:

Screenshot 2023-04-11 at 11 22 36 AM
Screenshot 2023-04-11 at 11 22 40 AM

**Comment by jjd330** [comment]
The way it's set up now, you need to set the signal parameters every time something besides 'A' changes. So after you set the flux_params here https://github.com/parsotat/NITRATES/blob/3c61ab44826626fbebe0f4a0430ca1c2f053e2ef/tests/test_likelihood_ratio_test_statistic.py#L304 , you need to set the signal parameters for the sig_bkg_mod. Like it's done here https://github.com/Swift-BAT/NITRATES/blob/main/do_llh_inFoV4realtime2.py#L467 .

**Comment by Tohuvavohu** [comment]
Thanks @jjd330 ! @metalphase speak up if anything is unclear :)

**Comment by metalphase** [comment]
@jjd330 That looks to have done the trick. Both versions of the test function are returning nearly identical values for sqrtTS for both IFOV and OFOV cases.
 
Screenshot 2023-04-11 at 11 52 37 PM

Screenshot 2023-04-12 at 12 04 20 AM

With that settled I will do some cleanup of the code.  It looks like the new test functions are also recognized and run using pytest. The IFOV passed while the OFOV test failed but the precision I'm demanding in my asserts are probably too high. What would be the appropriate precision in the asserts for the values of sqrtTS? @Tohuvavohu 

Screenshot 2023-04-12 at 12 04 36 AM

**Comment by Tohuvavohu** [comment]
@metalphase awesome! 
So it looks like they disagree at the 7th decimal place.
This is fine to accept (and is unsurprising) though it would be nice to know where it is coming from.
Since you are running the same codebase and the same python version for the two tests, it seems like it must be coming from the code somewhere...?

I'll note that the bkg_nllh also exhibits the same discrepancy. 
Does the nllh?
Don't spend too much time trying to track down where this is coming from, but understanding at least whether its from the new LLHwebins2 or the new Sig_bkg_model would be nice, if possible with reasonable effort.
Don't spend more than an hour on it.

**Comment by metalphase** [comment]
@Tohuvavohu between the two versions of the test script the values for bkg_nllh and nllh are consistent in both IFOV and OFOV scenarios. For IFOV, the bkg_nllhs were the same up to 11 decimal places and the nllhs to 6 decimal places. For the OFOV case it was 10 and 5 respectively. So it looks like nllh is more sensitive to whatever changes are happening as a result of LLH_webins2 and Sig_Bkg_model.

IFOV:
bkg_nllh =  46038.74332720732          ->   46038.743327207325
nllh         =  [45894.098830224066]    ->   [45894.09883014985]


OFOV:
bkg_nllh =  46038.74333109522          ->   46038.74333109522
nllh         =  [45917.71016714621]          ->   [45917.710166768826]    

Using the older test script as a baseline I attempted to investigate using LLH_webins with the Sig_Bkg_Model and using LLH_webins2 with the CompoundModel. In both cases I ran into some errors trying get the test script to run and spent some time trying to debug it so perhaps not worth spending so much time on it as you suggested. I'll save those separate test cases in a local copy in case we want to investigate further perhaps with some help from Jimmy. For now I just pushed the latest test script that sets the tolerances on the assert statements to 1e-07.

**Comment by Tohuvavohu** [comment]
@metalphase Ok, the fact that the residuals for the nllh are 1e5 times bigger than the bkg_nllh makes me think that the major contributor to the difference is likely coming in from the way the new model and likelihood interact with the minimizer.

Otherwise, I think things are looking good. 
Can you please copy in the output of running the tests, including run time, and warnings produced?
Then we can look at merging!

**Comment by metalphase** [comment]
The pytest finished with 2 passed tests and 725 warnings in 15.29 seconds of runtime. The majority of the warnings pertain to deprecation warnings such as using np.int instead of np.int64 or np.int32, or using np.bool in place of the built-in bool. I'll post some examples of these warnings, there's too many overall to post the entire output but pretty much all of the deprecation warnings fall under this category.

Screenshot 2023-04-13 at 11 51 40 AM
Screenshot 2023-04-13 at 11 51 48 AM

Other than that we have only two other warnings, one RuntimeWarning and one AstropyUserWarning. I think we captured those in the previous pull request but I'll paste them again:

Screenshot 2023-04-13 at 11 47 47 AM

Screenshot 2023-04-13 at 11 48 02 AM

**Comment by Tohuvavohu** [comment]
Ok, LGTM, i think can merge.
@jjd330 second look?

**Comment by jjd330** [comment]
Looks good to me too

**Comment by Tohuvavohu** [comment]
ok @parsotat you can merger if you are happy.

**Pull request merged**
