### PR TITLE
Creating test scripts for likelihood ratio test statistic calculation

### PR DESCRIPTION
**Pull request by metalphase**
Created a python script that performs the LLH ratio test statistic calculation for two sources, one IFOV and the other OFOV. The script and its necessary resources are contained in a new directory /tests

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Hi @metalphase,
Thanks, great work!
Can you please document here the output of the tests, some stats on runtime, and a better understanding of the warnings that are being produced?

Also, consider including profiling, ala : 
https://pypi.org/project/pytest-profiling/

**Comment by metalphase** [comment]
Sure thing @Tohuvavohu !

Running pytest on test_likelihood_ratio_test_statistic.py results in 2 passed and **725(!)** warnings after 26.94s. The majority of these warnings were DeprecationWarnings such as:


Screenshot 2022-11-22 at 9 51 40 PM


and:

Screenshot 2022-11-22 at 9 51 16 PM

However, among them were two other warnings, an AstropyUserWarning and a RuntimeWarning:
Screenshot 2022-11-22 at 9 53 07 PM

Screenshot 2022-11-22 at 9 52 43 PM


The runtime statistics from pytest-profiling are the following:

Screenshot 2022-11-22 at 9 41 19 PM

**Comment by Tohuvavohu** [comment]
Looks like the runtime warning is for this line:
https://github.com/parsotat/NITRATES/blob/2b5a30dc7a49be2c1dffefe883e44fc2c8fc37b6/nitrates/response/response.py#L1499 
Looks like its choking on the escape character '\', not sure why...

Anyway, looks like this PR adds ~200 MB to the repo, from the files required to store the 2 LOS responses.


Anyway
@jjd330 @parsotat 
Any thoughts here on these tests as implemented?

Do we want to also test any part of the bkg fitting (as discussed https://github.com/Swift-BAT/NITRATES/issues/5) ? 

if so, which part, or the whole script (it's probably too long)?(https://github.com/parsotat/NITRATES/blob/main/nitrates/llh_analysis/do_bkg_estimation_wPSs_mp2.py)

**Comment by Tohuvavohu** [comment]
Why did you close this PR @metalphase

**Comment by metalphase** [comment]
@parsotat , are you able to re-open this pull request?

**Comment by parsotat** [comment]
There seems to be a reopen and comment button but I am unable to actually click on it for  some reason.

**Comment by Tohuvavohu** [comment]
@metalphase can you figure out how to reopen this?

**Comment by metalphase** [comment]
Doesn't look like I can re-open this while I have another Pull Request open. I think I could close the new one that I opened and create a small commit and re-open this PR.

**Pull request closed without merging**
