### PR TITLE
Background fitting demo notebook

### PR DESCRIPTION
**Pull request by metalphase**
Adding a notebook, Example_Background_Fit.ipynb, which goes through the background fitting process for the particular background used in Example_LLH_setup_fixed_dirs.ipynb. The notebook essentially runs through the main function in do_bkg_estimation_wPSs_mp2.py in order to generate the background fit.

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Looking good, some comments:

"FOV of the craft" --> "FOV of BAT"

for figure of "Point sources within FoV"  please label the point sources with their names.

"Again, for no point sources in the POV" --> FOV

Your timeseries plots should all have triggertime defined as 0, so all times are relative to that. This is not how you have it set up, as is made obvious in Cell 64 "Location of trigger time and current tmid" where the triggertime is at t~24 seconds...
You seem to be subtracting 646018360 from all the event times. If this were the trigger time, then triggertime should be 0!

In these plots, why is 'tmid' not in the center of the signal time window?

For long run-time cells, warn the reader before execution of approximately how long it will take to run.

Cell 70,71,72, what times does the best background fit correspond to??

Cell 76 etc when displaying the model vs data dpis, make sure the plots are clearly labelled as "Model" or "Data"

Cell 77 and below, you should make sure to make these plots for the *same background time*, as you write
> Of course, in this specific comparison, we are using our own "eyeballed" background, so it may include more or less of the signal than the background fit.

Show the data that the model actually corresponds to! :)

**Comment by metalphase** [comment]
Regarding why tmid is not in the signal time window:

The signal time window is defined the following way in dp_bkg_estimation_wPSs_mp2.py in the main function. I took the latter definition since it overwrites the first definition for sig_twind. 

Screenshot 2023-01-17 at 9 02 01 PM

**Comment by metalphase** [comment]
@Tohuvavohu just pushed my latest revision of the background fitting notebook if you can check it out.

**Comment by Tohuvavohu** [comment]
Looking really really nice!

> For long run-time cells, warn the reader before execution of approximately how long it will take to run.

I don't see this, did i miss it somewhere?


Can you plot the data+model DPIs for the bkg fit side-by-side for easier comparison?
Can you use the same colorscale for them, so that the same count rate corresponds to the same color?

Almost there :)

@jjd330 thoughts?

**Comment by jjd330** [comment]
Haven't been able to take a very detailed look at this yet, but looks really good so far as a walk through of the process. Great work! 
Couple comments/questions so far,
Are you fixing Nsrcs = 1 just so it will run faster right now? It sounds like your saying it should be fixed to 0 or 1, but it should be the number of sources in the FoV (before do_init_bkg_wPSs is run). It's fine if you set it to 1 just so the notebook will run in an example as long as you're clear about that. 

For the plots showing the signal time windows and the bkg time windows at different tmids, I don't think it's quite clear what time interval is being used for the bkg fit. At the risk of making the plot look too bust, maybe making the regions being used for the fit another color that's listed in the legend or possibly describing it in text. 

print_ebin_dpi and print_low_vs_high_energy_dpi seem to be doing something weird in the loop over detx and dety. Replacing those loops with `dpi[bl_dmask] = rate_dpis[ebin]` should hopefully correct it and also make it run faster.

**Comment by metalphase** [comment]
@jjd330 I can visualize the gtis/btis in the following way. What do you think of this? I might just separate between bti and gti rather than the three sections as it is right now

Screenshot 2023-01-22 at 4 56 51 PM

**Comment by jjd330** [comment]
That looks great!

**Comment by metalphase** [comment]
Just commited the latest revisions to the notebook. @Tohuvavohu , let me know what you think of the fractional differences. For each energy bin I also calculated the average fractional difference across the dpis. The average fractional difference doesn't change much between energy bins so I'm not sure my claim that the background model undercounts compared the data really holds up anymore. I did the same thing for the low vs high energy bins and the average fractional difference does differ much more.

**Comment by Tohuvavohu** [comment]
Hi @metalphase 
This looks really nice!
So, given that your fractional difference is defined as (data-model)/data, and these results:
image

it looks like the bkg model fit is systematically *overpredicting* the flux by ~10% on avg, right?
But it's also clear that there is a significant tail of pixels in which it is underpredicting very significantly.
Thoughts @jjd330 ?

@metalphase it would also be useful to understand what the fractional difference distribution looks like, to see how common the outliers (yellows) really are...
Can you also plot histograms of the pixels by fractional difference? (np.hist the array of fractional differences, play with the bins number to find something informative)

**Comment by jjd330** [comment]
I'm pretty sure it's because of cell 47
`best_fit_t0 = best_fit_time - (exp / 2)`
`best_fit_t1 = best_fit_time - sig_wind/2.`
`best_fit_t2 = best_fit_time + (exp / 2)`
`best_fit_t3 = best_fit_time + sig_wind/2.`

and the next cell where you divide the DPI by `exp`. `exp` was how much exposure there was in the bkg fit with the signal window already taken out. In cell 47 it should by +/- `bkg_dur/2.` which you define in cell 32

**Comment by metalphase** [comment]
@jjd330 ah that would do it, so I presume then that I'd have those time variables set up as:

best_fit_t0 = best_fit_time - (bkg_dur / 2)
best_fit_t1 = best_fit_time - sig_wind/2.
best_fit_t2 = best_fit_time + (bkg_dur / 2)
best_fit_t3 = best_fit_time + sig_wind/2.

For cell 48 when I'm dividing by the exposure, I am trying to compare the count rates between the model and data for equivalent GTIs. If that is the case, shouldn't I be taking the exposure (with the signal window excluded) in order to match the GTI for the model?

**Comment by jjd330** [comment]
Yes, for cell 48 you should still divide by the exposure. The change you've outline there should fix it. The data you're selecting should line up with the exposure calculated during the fitting now.

**Comment by metalphase** [comment]
Implemented those changes as outlined above and plotted the histograms for each of the fractional difference dpis. Does not look like there have been any change in the average fractional difference for each ebin. The histograms look to confirm that there is a systematic overcount by the model. Additionally, beyond the first energy bin, the fractional differences histogram clusters at nearly half-integer steps until the final two energy bins. This clustering does not seem to be due to the number of bins in the histogram as increasing the number of bins does not affect the clustering.



Screenshot 2023-01-24 at 10 41 35 PM
Screenshot 2023-01-24 at 10 41 43 PM
Screenshot 2023-01-24 at 10 42 05 PM
Screenshot 2023-01-24 at 10 42 16 PM

**Comment by Tohuvavohu** [comment]
Nice!
You are including all of the detectors in your statics (average, fractional difference) , even the ones that have 0 counts by nature of the detector mask (dmask). 
This is biasing the abs(fractional difference) towards 0!
Because the model knows the dmask, and the dmask is mostly made up of  detectors from the data with 0 counts...
So 0-0 is sure to be 0, and the match is not due to the modelling.

Remake the fractional difference statistics, but only using the detectors in bl_dmask.
Also remember to apply the dmask to the data when you assemble in cell 47.

Recall, `ndets = np.sum(dmask==0)=14932` detectors that are actually being used in this analysis!

Recall also that the total number of detectors in the array is 32,768 so if your histogram suggests there are more detectors than this...there's some problem.
@jjd330 are there more pixels than that in these arrays because you are actually just pretending there are detectors with 0 counts in the gaps between detector blocks?
`xbins = np.arange(286+1) - 0.5`
`ybins = np.arange(173+1) - 0.5`

This inflates the # of array elements by a factor of ~1.5

**Comment by jjd330** [comment]
Oh what I said to put in was still wrong. It should be,

best_fit_t0 = best_fit_time - (bkg_dur/ 2.) - (sig_wind/2.)
best_fit_t1 = best_fit_time - (sig_wind/2.)
best_fit_t2 = best_fit_time + (bkg_dur/ 2.) + (sig_wind/2.)
best_fit_t3 = best_fit_time + (sig_wind/2.)

You can print out `(best_fit_t1 - best_fit_t0) + (best_fit_t2 - best_fit_t3)` and make sure it matches `exp`

**Comment by jjd330** [comment]
And yes, Aaron there are more pixels than dets because it includes the gaps.

**Comment by Tohuvavohu** [comment]
Hi @metalphase , this is looking good, almost there!
After applying filter_evdata you should be left with eventdata using 14932 good detectors to use in this analysis.

However, you are then casting it as a DPI, with an array which has dimensions 286*173=49478 cells.
Of course, in the whole BAT detector plane there is only 32,768 detectors...what is going on?
The reason for this is that the BAT detector plane is not completely filled with detectors! 
The blocks of detectors are arranged in rows and columns, with gaps between them for the necessary readout electronics, etc.
See below
image

And so you see the 'filling factor' is only about (32768/49478) = 2/3. 
So most of your cells in the DPI array are not actual detectors, they are space fillers, and therefore will always have 0 counts.

So what you want is to perform your statistics (avg fractional difference, histogram of difference, etc) only on detectors that are in bl_dmask. Does this make sense?

**Comment by metalphase** [comment]
@Tohuvavohu just pushed the latest changes which applies bl_dmask for the fractional difference dpis. I still use the original fractional difference dpi for the visualization of the dpi image but for the histogram and average fractional difference I use the filtered fractional differences.

**Comment by Tohuvavohu** [comment]
@metalphase great job screening out all the fake detectors. 
Can you confirm that you have 14932 detectors in your statistics?

Also, in your comment in cell 50 you define
`# Fractional Difference DPI
# (data-model)/data`
but looking at the code you seem to actually be doing (y1-y2)/y2 = (data-model)/model


I think @jjd330 wanted to take a look also

**Comment by jjd330** [comment]
Looks like the bkg window you used for fitting and used for the fractional difference plots are slightly different and might be why the averages aren't closer to 0. 
In cell 37 during the fitting you have 
    bkg_t0 = tmid - sig_wind/4. - bkg_dur/2.
    bkg_t1 = tmid + 3.*sig_wind/4. + bkg_dur/2.
and in cell 47 where you're getting the data for the fractional differences you have
  best_fit_t0 = best_fit_time - (bkg_dur/ 2.) - (sig_wind/2.)
  best_fit_t1 = best_fit_time - (sig_wind/2.)
  best_fit_t2 = best_fit_time + (bkg_dur/ 2.) + (sig_wind/2.)
  best_fit_t3 = best_fit_time + (sig_wind/2.)
Try having the same exact start and end times and see how the fractional differences look. 
And make sure that `(best_fit_t1 - best_fit_t0) + (best_fit_t2 - best_fit_t3)` is the same as `exp`. 

I think because best_fit_t0 is before the start of the data and bkg_t0 is just after the start of the data so you're using less actual livetime than what your `exp` is.

**Comment by metalphase** [comment]
Ah, good catch on the inconsistency of  best_fit_t0 and best_fit_t2, I fixed those up to have the same values as used for bkg_t0 and bkg_t1 during the for loop. In cell 47, I print the value for `(best_fit_t1 - best_fit_t0) + (best_fit_t2 - best_fit_t3) ` as well as `exp` and get the same values, so at least we are working with equivalent amounts of time. 

@Tohuvavohu yeah, that's definitely a mistake in the calculation for the fractional differences. I replaced the divisor with the data dpi rather then the model dpi. I've also printed out the size of `fractional_diff_bl_dmask` for each of its calculations and get a size of 14932 each time. 

With all said and done, the averages have gone back to being pretty poor with exception to energy bin 171.5keV - 245.0keV. 
Screenshot 2023-01-31 at 11 39 53 PM

**Comment by Tohuvavohu** [comment]
Thanks @metalphase 
So thinking about this from the basics here:
we have a total bkg count rate of ~6800 ct/s and 14932 detectors, which gives us an avg rate of ~0.5 ct/det/s.
The exposure for your bkg fit is ~60 seconds, so each detector should have ~30 counts over the whole period.

We have 9 energy bins, but counts are not uniformly distributed in energy, so in the high-energy bins each detector likely have ~or 1 counts over the whole period.
Remember, our count data are quantized, not continuous! And the fractional difference of 2 vs 1 counts is -1.... so a fractional difference of 0.25 doesnt seem very bad to me!
Maybe easier to interpret in absolute difference (so it remains in units of counts) instead of fractional?

But i know @jjd330 expects the fit to be doing better. Do you think we should continue to investigate?

**Comment by jjd330** [comment]
Yeah, I guess difference divided by data at such low counts is not a great measure. It also ignores all the dets with 0 counts. Divided by the model would probably be better since it's not 0, still not great since because of low counts though. 
Like Aaron said, maybe absolute difference instead of fractional could be good too. Maybe seeing a difference of the total (summed over all dets) would be good too (so not a plot just a number).

**Comment by Tohuvavohu** [comment]
Ok @metalphase can you do absolute (instead of fractional) difference plots and histograms?
And also calculate the total count difference summed over all detectors.

@jjd330 remember also that this fit isn't great because its only using 1 source (Sco X-1) in the fit, and i think there are 7 IFOV, 4 of which have TS>7...
@metalphase what is the runtime with Nsrcs=2? the fit should improve with more of the sources fit... 
but if Nsrcs=2 takes too long, you can just show the analysis difference and explain that it is due to the incomplete point source fitting.

To prove this point, you could just take the results of the whole bkg fit with all the sources  that was already run (stored in bkg_estimation.csv or wherever) and repeat the DPI comparison with that.

**Comment by jjd330** [comment]
Yeah, more sources might be good to have in the example notebook anyway, but I don't think they'll make a huge difference here. 
The issue I see is that the average difference should be close to 0 even with missing PSs since the fit should be able to get the total rate correct (more diffuse to compensate missing PSs), and the "bad model fit" would be apparent in an increased standard deviation of the differences. Though again with low counts it's hard to get a good measure of the spread of the distribution / standard deviation.

**Comment by metalphase** [comment]
@Tohuvavohu The last time I tried running with Nsrcs=2 I let it run overnight and it was still ongoing the next afternoon. I'll implement the absolute difference and try the prior comparison with the completed background estimation.

For the total count difference, would I be looking at the data counts - expected model count for each detector and then summing up for each detector?

**Comment by Tohuvavohu** [comment]
@metalphase 
It shouldn't take nearly that long! I thought you had said you ran it in ~1 hour before?

The absolute difference looks good...but it will be easier to interpret if the DPIs are actually integrated count (not rate) DPIs, because then the absolute difference will also be in units of counts! 
Can you make the count DPIs (multiply rate by exposure) and rerun the stats on those?

re total count difference: just add up all the counts across the DPI (per energy bin) for both the model and data individually, and report the numbers.

**Comment by metalphase** [comment]
Not sure what was special about that particular run but every other time I've tried it, I've never been able to finish the run. 

I've redone the absolute differences in terms of counts instead of the count rates. For the total count we have 384107 counts for the data and 387642 for the model in total.

**Comment by Tohuvavohu** [comment]
@metalphase something is weird!
The absolute differences in units of counts should be integers only (integer-integer=integer) there are no 0.5 photons...what's going on?

Can you break the total down by energy bin?

**Comment by Tohuvavohu** [comment]
Ah, also, don't take the absolute value of the difference! 
Sorry this was unclear, i should have been more careful with my language.
 when i said 'absolute difference' i just meant to distinguish it from the 'fractional difference'. 
We want to see the full sign of the differences, the shape of the distribution! so just data-model.

**Comment by metalphase** [comment]
Yeah, that's right... it should only have integer values. However the only thing I've done to convert from count rates to counts was to multiply the rate dpis by the exposure (~61.44s) so the distribution of the histogram shouldn't be much different from that of the count rates, right? 

In the breakdown of model count and data counts per energy bin, even though they're floating point numbers, they're all within a small round up from being integer valued.

**Comment by Tohuvavohu** [comment]
Yeah, the shape of the distribution is interpretable now. 
Have to think a bit about whether its performance is as expected though... @jjd330 

I think your non-integer counts are coming fromthe *small* difference in the exposure (used in the model) and the bkg 
image
perhaps? maybe try to use this instead?

If that doesn't work, you can try to force the model DPI by rounding all the values to the nearest integer.

**Comment by jjd330** [comment]
The individual energy bins look more reasonable now, with average differences being all <0.1 counts. I'm not quite sure why the <64 keV and 64-350 keV ones have a larger difference though. The <64 keV is about 10 times higher than all it's energy bins added together and I'm not sure why.

**Comment by metalphase** [comment]
Ok, I forced the model dpis to be integer valued and the graphs are looking more intuitive, at least as far as I can tell. @Tohuvavohu 
Screenshot 2023-02-04 at 1 07 40 PM

As for trying to compare with the bkg model from bkg_estimation.csv. It looks like my method of generating the model dpis from using the following process: 

`final_bkg_and_src_mod = Bkg_and_Point_Source_Model(solid_angle_dpi, ebins, rt_obj, bl_dmask, src_tab['Name'], bkg_row=bkg_params)
rate_dpis = final_bkg_and_src_mod.get_rate_dpis(bkg_params)`

won't work since bkg_estimation.csv does not include any of the error background rates. That prevents me from creating a Bkg_and_Point_Source_Model object and hence the dpis. I'll try to see if there is any other background+source model that I might use to create the dpis that doesn't require the error rates

**Comment by Tohuvavohu** [comment]
@metalphase 
Reference the "example LLH setup" notebook you first worked on, where the bkg_estimation.csv is parsed. There you create a CompoundModel object which has a class function 'get_rate_dpi/s/error'.

**Comment by metalphase** [comment]
Ok, got that to work and repeated the analysis for the background fit in bkg_estimation.csv. A couple of things:

1 - The background fit in bkg_estimation.csv leads to less overcounting in the model between 15keV-64keV. Between 64-350keV we have the same number of counts as with the background fit just one source. I'm wondering if the benefits of the extra sources is limited to the 15-64keV range.

2 - For either of the models we count exactly 29864 counts for each of the 64.0keV-84.0keV, 84.0keV-120.0keV, 120.0keV-171.5keV. Why is this number consistent across these energy bins? 

3 - Since none of the bkg_estimation.csv model counts differ in the 64.0keV-350.0keV range the average absolute difference in the >=64.0keV range is the same. For <64.0keV, we are overcounting less compared to the previous model.

**Comment by Tohuvavohu** [comment]
Great job!
1) This makes sense! 
From the paper: 
image
soft means proportionally more low-energy photons than high energy

2) I don't know! This is weird... paging @jjd330 
29864 = 14932 x 2, which seems like an unlikely coincidence. 
How are you doing the rounding? You should investigate.
before rounding these were your values (from commit https://github.com/parsotat/NITRATES/commit/b153a3c53392d45e043b38e9d0d978d71fe01691)
image

after the rounding commit:
image


3) Good!

**Comment by metalphase** [comment]
@Tohuvavohu I previously applied np.round to the count dpis (y1_bl_dmask and y2_bl_dmask). I think that was the issue. In this latest commit I round only after summing up the counts in the dpis. The results don't have that regularity in the model counts, so I think we're good on that front.

**Comment by Tohuvavohu** [comment]
Looking better! I think this notebook is close to done :)

1. In your text between cell 59 and 60 (which I think should actually be before cell 59) you reference the 7 sources that are in the FoV, but the careful reader might notice that there are only 4 actually included in the model. 
Explain why this is to your reader!

2. Can you think of a good way to quantitatively compare the two models (1 vs 4 sources) to each other and how good they are at fitting the data?

**Comment by metalphase** [comment]
Added some text to explain the decrease from 7 -> 4 sources. 

So, thinking out loud here... We can't evaluate the model performance based on total count since the total count doesn't care where the counts were registered. Which is why we have the absolute difference dpi since it considers whether the counts registered were registered where we actually saw them in the data. And calculating the absolute difference per ebin also considers that the counts registered were also done so within the correct ebin (as opposed to calculating the absolute difference for the entire count DPI). So the average absolute difference would tell us, on average, by how many counts we counted more/less per detector across the whole detector plane. For the purposes of comparing model to model, whether we counted more vs whether we counted less is not as important as whether the average absolute difference is close to zero. (Though the knowledge of consistent overcounting or undercounting tells us about our model's performance in itself). So the sign of the average absolute difference is not important. But we'd want to see that, in magnitude, the average absolute difference is close to zero. 

So we have 9 average absolute differences for each ebin all of which we ideally would like to see their absolute values reach 0.0 in value. We could possibly sum up the absolute values of the average absolute differences. If the model count dpis are equivalent to the data count dpis for each ebin, then for each ebin we'd have 0.0 in average absolute difference. Summing them up and we'd get 0.0 for our lowest bound and the score for a perfect model. If our model count dpis differ from our data count dpis as they do in our notebook, then that number is larger than 0.0. 

So perhaps we can say that a model where the sum of the absolute values of the average absolute differences is closer to zero is better. But the problem is that it doesn't really distinguish under/overcounting and the upper bound for this measure is not really intuitive (what's the worst that we could score for each ebin...) and it is not intuitive how much better something scoring 3.0 is to something scoring 2.0.

In any case, I tried this with the 1 source model and for the 4 source model which scores as follows: 

1 Source Model:
Average absolute difference:  -0.09710688454326279 for energy bin 15.0keV - 24.0keV
Average absolute difference:  -0.08130190195553175 for energy bin 24.0keV - 35.0keV
Average absolute difference:  -0.1819582105545138 for energy bin 35.0keV - 48.0keV
Average absolute difference:  -0.07956067506027324 for energy bin 48.0keV - 64.0keV
Average absolute difference:  0.19086525582641306 for energy bin 64.0keV - 84.0keV
Average absolute difference:  0.21859094562014467 for energy bin 84.0keV - 120.0keV
Average absolute difference:  0.085654969193678 for energy bin 120.0keV - 171.5keV
Average absolute difference:  -0.42104205732654704 for energy bin 171.5keV - 245.0keV
Average absolute difference:  0.10762121618001608 for energy bin 245.0keV - 350.0keV
1.4637021162603805

4 Source Model:
Average absolute difference:  -0.0668363246718457 for energy bin 15.0keV - 24.0keV
Average absolute difference:  -0.05960353603000268 for energy bin 24.0keV - 35.0keV
Average absolute difference:  -0.06891240289311545 for energy bin 35.0keV - 48.0keV
Average absolute difference:  -0.026118403428877578 for energy bin 48.0keV - 64.0keV
Average absolute difference:  0.19086525582641306 for energy bin 64.0keV - 84.0keV
Average absolute difference:  0.21859094562014467 for energy bin 84.0keV - 120.0keV
Average absolute difference:  0.085654969193678 for energy bin 120.0keV - 171.5keV
Average absolute difference:  -0.42104205732654704 for energy bin 171.5keV - 245.0keV
Average absolute difference:  0.10762121618001608 for energy bin 245.0keV - 350.0keV
1.2452451111706402

It's not definitive, but empirically it looks like it works in this example.

**Comment by metalphase** [comment]
Actually, thinking about it a bit more, I could see if I can remove each of the sources in the complete background model to compare between 1, 2, 3, and 4 models

**Comment by Tohuvavohu** [comment]
Right, so we know that the 4 source model is better than the 1 source model (if the analysis is working correctly!) for reasons you describe way up top in the notebook (the analysis checks whether adding more sources improves the model).
The test statistic tells you precisely which of the models is preferred by the data! 
What is the DeltaLLH for the 1,2,3,4 source models?
But this is just a description of the relative quality. 
It won't tell us whether the total fit is any good or not really suitable.... @jjd330 ?

Your idea about the sum of the absolute avg differences
$\Sigma_i^{ebins} Abs(Mean(\Sigma_j^{Ndet}(Data_{ij}-Model_{ij})))$
is an interesting one. It would be interesting to see if the trend holds for 1,2,3,4 detectors...

One thing that we haven't looked at:
Are there particularly problematic detectors?  Or particulary problematic subset of the detector plane? 
That is, is the data-model residual dominated by a small fraction of the total detector plane?
Is the model better for some part of the detector plane than others?

One way to find out is to try taking subsets of the detector plane and seeing whether there is a statistically different model residual (histogram of differences, or other test) for each.

**Comment by jjd330** [comment]
Re: this https://github.com/parsotat/NITRATES/pull/6#issuecomment-1418376246 , why are the model counts being rounded? They're not supposed to be integers. 

Re the current comments: Sounds like what you want @Tohuvavohu, is a goodness of fit measure (like a chi2), which unfortunately doesn't exist for a Poisson distribution. You could just look at the variance of the residuals and say lower variance is better, if you don't need an something more formal. You could also either do all the energy bins at once or bin near by detectors (possibly by sandwich) so that there's enough counts in each detector that you can use the normal approximation of the Possion distribution and do a chi2 goodness of fit test.

**Comment by Tohuvavohu** [comment]
Oh @jjd330 the model gives back non-integer counts? Somehow i didnt realize this. Why?

**Comment by jjd330** [comment]
It's the expectation value of the distribution, not the number of counts you expect to get. If there's 1 count / s, in 2.5 s the expectation of the model should be 2.5 counts.

**Comment by metalphase** [comment]
I take it then that I should revert back from forcing the counts to be integer valued?

**Comment by Tohuvavohu** [comment]
Seems like it, sorry @metalphase ! I must have forgotten about this.
Anyway, all the other convo is still relevant.

**Comment by metalphase** [comment]
@Tohuvavohu right so we mentioned a while back that we have two sub-arrays that seem to be undercounting relative to their neighbours. These sub-arrays should be the DETX=[112,128] DETY=[48,56] and DETX=[224,240] DETY=[40,48]. So I could repeat calculating the absolute differences with these sub-arrays excluded. I can see if I can mock up a function that returns the DPI after excluding a specified subset.

**Comment by Tohuvavohu** [comment]
@metalphase 
please explain in the notebook for the future reader (or me when I forget) why the counts are non-integer!

doing again with those sub-arrays excluded sounds good, but those are just ones that we could see by eye might be problematic!
What do you think about a systematic search for subsets of the detector plane that might be poorly modelled by excluding part-by-part and comparing the model expectations (variance of the residuals or absolute difference of total counts or whatever)?
This could look like dropping one DM or sandwhich or whole block from the detector plane at the time, recomputing the statistics, storing them, and then repeating in a loop across the whole array....
Thoughts?

**Comment by metalphase** [comment]
@Tohuvavohu agreed, it'd be a lot more general purpose to create a systematic search over the detector plane. So perhaps I can implement a function that returns the data after excluding the counts from a specified subset, likewise for the model. Then implement another function to calculate the variance of the residuals or absolute differences after the exclusions. Afterwards I can wrap it with a for loop. Could you explain what you mean by DM/Sandwich?

**Comment by Tohuvavohu** [comment]
Sorry, i'm just throwing jargon around!
A sandwhich is 128 detectors, half a Detector Module (DM). 
A DM is 256 detectors, and is 1/8th of a block. A block is  1/16th of the detector plane.
The blocks are numbered 0-15 going clockwise from top-left of the detector plane.

image

image

**Pull request closed without merging**
