### PR TITLE
Adding new background fitting notebook.

### PR DESCRIPTION
**Pull request by metalphase**
Apologies for the new PR but the previous branch had some gnarly merge conflicts. For context into the discussion on the notebook contents, you can refer to the previous PR: https://github.com/parsotat/NITRATES/pull/6. 

New Additions:

Added a new cell that recalculates the absolute diffs and variances of the residuals after masking off each block one-by-one.

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Looking good!
What's the conclusion, does removing any of the blocks substantially improve the fit quality?

**Comment by metalphase** [comment]
@Tohuvavohu 

The first thing to note is that between having only one source in the background vs the full background with all source we somehow see a big jump in the average absolute differences for energy bins 15keV-24keV and 24keV-35keV. For example, comparing the background that includes Sco X-1 with the full background fit, we have the following average absolute differences and variances of the residuals for the two energy bins:



  | 1 Source in FOV Sco X-1 |   | Full Background
-- | -- | -- | --
15keV-24keV |   |   |  
Average absolute difference | -0.0974419783199677 |   | 1.26034684620608
Variance of Residuals | 8.02474358106652 |   | 9.1707019289505
24.0keV-35.0keV |   |   |  
Average absolute difference | -0.0645592221561206 |   | 0.174439729435887
Variance of Residuals | 4.67665821873792 |   | 4.66708425042423

I'm assuming we prefer smaller average absolute differences and variances. For other energy bins, the full background model is only slightly larger in magnitude than the 1 source background. Since the data is all the same, it's as if the additional point sources are suppressing the number of counts in the model if I am reading into this correctly. Nonetheless, it does look like this increase in the average absolute difference is compensated by the variance also increasing. I've also compared with other 1-source background models using point sources other than Sco X-1 and seen similar results. 

For removing blocks, obviously the choice of the block matters so removing block '0' had the effect of raising the average absolute differences across all energy bins with very small increases in the corresponding variances in the residuals. I take that to mean that the fit is objectively worse than the full background fit. As noted in the previous PR, we had suspected undercounting in the regions bounded by DETX=[112,128] DETY=[48,56] and DETX=[224,240] DETY=[40,48]. These correspond to the selections of blocks '11' and '14 respectively. After removing block '11', the average absolute difference decreases for all but one of the energy bins. Likewise the variances of the residuals all slightly decrease except for one energy bin.  Removing block '14' on the other hand had almost no effect in comparison to the full background dpi so there was not much advantage to removing that block compared to block '11'.

Not sure how illuminating it is, but I've compiled the averages and variances for the various scenarios above into a spreadsheet to see how the averages and variances look across all the energy bins.
















[BlockRemovalStats.csv](https://github.com/parsotat/NITRATES/files/10832564/BlockRemovalStats.csv)

**Comment by Tohuvavohu** [comment]
@metalphase
Thanks for looking into this.
It sounds like you are saying that the 1 source fit is better than the 4 source fit, with respect to these metrics, yes?
It's not obvious to me why this should be happening, but maybe @jjd330 has some ideas.

Does removing block 11 improve the quality of the fit more than removing any other block? 
Would the increase in fit quality have been remarkable relative to the other blocks if you didnt already suspect a problem with block 11?
Can you show the statistics of the fit with the whole det plane and with Block 11 removed, so we can take a look?

Can you further subset the blocks into smaller regions and test the fit just for block 11 but with different DMs removed?

PS - your BlockRemovalStats.csv is not a properly formatted CSV, or at least not one I can open.a

**Comment by metalphase** [comment]
[BlockRemovalStats.csv](https://github.com/parsotat/NITRATES/files/10832904/BlockRemovalStats.csv)

hopefully this .csv works this time

**Comment by metalphase** [comment]
@Tohuvavohu yeah, it looks as though the 1 source fit is better under these metrics.  But in general, we'd need another metric to evaluate any differences made by any of the masking of the blocks/DMs. This ties into the your new request on blocking just the DMs from block 11. 

Screenshot 2023-02-26 at 12 12 10 AM


This is a screenshot of the table comparing the same metrics between the full background, the bottom 3 DMs of block 11, and the particularly problematic DM that we identified in DETX,DETY coordinates: [108,144], [66,77]. I stopped at these DMs because as you can probably already tell it's hard to identify visually which one was the actually problematic DM. In each case, some of the metrics are lower than the full background but some are still higher. The differences are very subtle.

**Comment by Tohuvavohu** [comment]
@metalphase I can't and won't read this table! :) 
I suggest you come up with a way to visually show the relative fit quality.
By 'full bkg' you mean just for block 11, right?
Are any of the differences significant compared to the others?
also reference my questions from previous comment above.

re: 1 bkg src vs 4 bkg src fit
I thought this was for the whole detector plane, not having anything to do with masking the blocks, right?

**Comment by metalphase** [comment]
@Tohuvavohu

> By 'full bkg' you mean just for block 11, right?

 "full bkg" is bad terminology on my part, I mean to use "full detector plane", i.e. none of the block/DMs are masked off.

> Are any of the differences significant compared to the others?

I'd say so but it's also that the fit is better for far more energy bins than just a singular energy bin. For example for energy bin 24keV-35keV, removing block 2 has an average absolute difference of 0.166458758596031 compared to 0.176048839725806 after removing block 11. But for every other energy bin, block 11 yields smaller average absolute differences. So overall, it looks like removing block 11 is a better choice

Addressing other questions:

> Can you further subset the blocks into smaller regions and test the fit just for block 11 but with different DMs removed?

 I think I misinterpreted your request with subdividing into DMs. Instead you want me to mask off everything but block 11 and then each of the DMs one-by-one to test the impact each DM has on the overall fit of block 11. Is that right?


> Does removing block 11 improve the quality of the fit more than removing any other block?
Would the increase in fit quality have been remarkable relative to the other blocks if you didnt already suspect a problem with block 11? 

I think upon visual inspection of the average absolute differences, removing block 11 does improve more than other blocks. After removing block 11 the average absolute differences are smaller compared to the full detector plane for more energy bins then other blocks. But, to the latter question's point, this was anticipated and I'd need to come up with a better way to show the relative fit quality as you described. 

Perhaps I can provide a histogram of (average absolute difference for full detector plane) - (average absolute difference after removing block i) for each of the energy bins. So a better fit should see more negative values in the histogram. Only issue would be the relative importance of having a good fit in one energy bin vs another. I.e does it matter more to have a better average absolute difference in the ebin 15keV-24keV vs 245keV-350keV? I wonder if summing up the differences of the average absolute differences might be a good metric to evaluate the overall advantage of removing a block.

>Can you show the statistics of the fit with the whole det plane and with Block 11 removed, so we can take a look?

Screenshot 2023-02-26 at 4 59 19 PM

**Comment by Tohuvavohu** [comment]
All of your numbers have way too many sig figs! 

> I think I misinterpreted your request with subdividing into DMs. Instead you want me to mask off everything but block 11 and then each of the DMs one-by-one to test the impact each DM has on the overall fit of block 11. Is that right?

Correct

> I think upon visual inspection of the average absolute differences, removing block 11 does improve more than other blocks. After removing block 11 the average absolute differences are smaller compared to the full detector plane for more energy bins then other blocks. But, to the latter question's point, this was anticipated and I'd need to come up with a better way to show the relative fit quality as you described.

What is the reduction in variance+differences of removing block 11 from the fit **compared to the other blocks**?
Is the size of the effect significant given the variance of the variances?

**Comment by jjd330** [comment]
In cell 110 where you're reading in the pre-fit bkg model, you left the line `ps_mods = ps_mods[:1]` in, so you're only using 1 of the 4 sources.

**Comment by Tohuvavohu** [comment]
What's the result here? 
What is the reduction in variance+differences of removing block 11 from the fit compared to the other blocks?
Is there any DM in Block 11 that is particularly bad?

**Comment by metalphase** [comment]
@Tohuvavohu  sorry for the long wait. The model should make use of all 4 sources now.

**Comparing Block Removals**
To compare the effect of removing each block to each other I have done two things:

1 - Calculated the sum of the differences of the average absolute differences between the full detector and the detector - block. 
2 - Calculated the change in the variances between the variances for the full detector plane and the variances after removing a block.

For any of the changes in either the average absolute differences or the changes in the variances, +ive changes imply that the model performed better after removal of the block. The sum of the changes in the average absolute differences gives a measure of the overall change in the average absolute differences.

After the removal of almost every block, the sum of the changes in the average absolute differences were within the range of +-0.1. The one exception actually occurred for block 11 which was actually the worst performing by this metric with a sum of -0.11. For the changes in the variances, their changes were negligible and in many cases their rounding truncated the changes to just 0.0. For all but a few energy bins, the changes in the variances were within the range of +-0.02.


**Comparing DM Removals**

Isolating the DMs leads to sums of the change in average absolute differences being all within the range of +-0.14. The removals of what I named DM id 5 and id 3 had the strongest fits with changes of +0.09 and +0.08 respectively. These correspond to DETX,DETY coordinates of ((108,144),(55,66)) and ((108,144),(33,44)) respectively. DM id 5 includes the sandwich that we suspected of undercounting though I did not expect that there was anything particularly wrong with the amount counted by DM id 3. The changes in the variances for DM id 5 though is all negative, so the variances are larger after removing that DM. The changes in the variances after removing DM id 5 were also all larger than the respective changes in the average absolute differences.

**Comment by Tohuvavohu** [comment]
@metalphase Thanks for your investigation here!
It's not obvious to me what the takeaway is here, I think we need to be thinking in a more statistically principled way about how to tell if the model is worse for different detectors...

Can you start a separate notebook where you just read in the background_estimation.csv and then move everything from from "Masking Off Blocks From Detector Plane" and down into that notebook?

That will leave the Example_Background_Fitting notebook to just show what the script is doing and basic quality checks.
Once you've done that, I think we can merge this for now, and think about returning to this question later, after the testing framework is done.

**Comment by metalphase** [comment]
@Tohuvavohu Applied those changes to the notebook and separated the new content into a new one. I agree, the bottom line was that it's not easy to distinguish the differences for the removals of different blocks. It is not obvious if the changes in the average absolute differences are significant when taken together with the changes in variances. Comparing the even smaller differences between the average absolute differences after removing each of the blocks is less obvious still.

**Comment by Tohuvavohu** [comment]
Ok, add the new notebook to this PR and then we will merge

**Comment by metalphase** [comment]
@Tohuvavohu Done!

**Comment by Tohuvavohu** [comment]
@metalphase i dont think 'Masking_Detectors.ipynb' needs to repeat everything in the main Bkg fitting tutorial notebook.
instead just read in the background_estimation.csv and start at Cell 50.

**Comment by metalphase** [comment]
@Tohuvavohu Shortened it just to include the relevant sections.

**Comment by Tohuvavohu** [comment]
LGTM. @parsotat can you please merge when you get a chance

**Pull request merged**
